#!/usr/bin/env python
import argparse
import sys
import tortp

def main(arg):
   parser = argparse.ArgumentParser()
   parser.add_argument("do", help="start | stop | new | info")
   args = parser.parse_args()
   if args.do == "start":
      tortp.start(tortp.tortp_dir(tortp.get_home(tortp.check_user())))
   if args.do == "stop":
      tortp.stop(tortp.tortp_dir(tortp.get_home(tortp.check_user())))
   if args.do == "new":
      tortp.tor_new()
   if args.do == "info":
      tortp.exit_info()
   if args.do != "start" and args.do != "stop" and args.do != "new" and args.do != "info":
      print 'Type "tortp.py -h" for options'

if __name__ == '__main__':
   main(sys.argv[1:])
